### ISSUE TITLE
Критическая ошибка в 12.07 (ice.soye@gmail.com)

### ISSUE THREAD

**Issue by icesoye** [sbprov2/SBProV2#329]
Описание.
1. Запускаем прогу.
2. Выбираем Workspace
3. Пока грузится воркспейс, открываем еще одну вкладку и выбираем для загрузки фьюч (у меня был 6J) и нажимаем apply.
4. SB падает/останавливается

Ошибку удалось повторить 3 раза.

Скрин - http://prntscr.com/c60kw0

Код ошибки
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at SBProV2.MainClasses.LoadWorkSpace.BackgroundWorkerDoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SBProV2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/SBProV2/SBProV2.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Telerik.WinControls.UI
    Assembly Version: 2015.3.930.40
    Win32 Version: 2015.3.930.40
    CodeBase: file:///C:/Program%20Files%20(x86)/SBProV2/Telerik.WinControls.UI.DLL
----------------------------------------
Telerik.WinControls
    Assembly Version: 2015.3.930.40
    Win32 Version: 2015.3.930.40
    CodeBase: file:///C:/Program%20Files%20(x86)/SBProV2/Telerik.WinControls.DLL
----------------------------------------
TelerikCommon
    Assembly Version: 2015.3.930.40
    Win32 Version: 2015.3.930.40
    CodeBase: file:///C:/Program%20Files%20(x86)/SBProV2/TelerikCommon.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Telerik.WinControls.Themes.VisualStudio2012Light
    Assembly Version: 2015.3.930.40
    Win32 Version: 2015.3.930.40
    CodeBase: file:///C:/Program%20Files%20(x86)/SBProV2/Telerik.WinControls.Themes.VisualStudio2012Light.DLL
----------------------------------------
Telerik.WinControls.Themes.VisualStudio2012Dark
    Assembly Version: 2015.3.930.40
    Win32 Version: 2015.3.930.40
    CodeBase: file:///C:/Program%20Files%20(x86)/SBProV2/Telerik.WinControls.Themes.VisualStudio2012Dark.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1082.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by icesoye** [comment]
я вам так ошибки кидать буду и релиз после 15.08 не выйдет никогда :DDD

**Comment by sbprov2** [comment]
Только что вышло обновление, там у вас выбрать ничего не получится. Пока грузится workspace или график, выбор или создание вкладок недоступно.
